# 作业2：纯天然手工制作神经网络

本次作业中，你将体验到如何用最基本的矩阵运算来实现一个前馈神经网络。在该实现中，唯一需要使用到的软件包是Numpy。

### 第1题

利用 Git 的基本操作，对第一次作业进行一次修订。具体要求如下：

1. 将库的名称统一为 “ai2021s”。
2. 在库的根目录创建文件夹 `HW1`，将第一次作业提交的 Notebook 文件重命名为 `numpy_practice.ipynb`，并移至 `HW1` 文件夹中。
3. 提交这一修改，提交信息为 “reorganizing project files”。
4. 从本次作业起，均按上述规则建立文件夹。本次作业的文件名为`fnn.ipynb`。
5. 优化作业1中各函数的编写，直接对原始文件修改并利用 Git 命令提交。根据本次修改的结果，你将对作业1获得最多20分的加分。

### 第2题

(a) 根据作业1的内容，编写**数值稳定**的函数 `sigmoid(x)` 和 `softplus(x)`，要求它适用于 Numpy 向量和矩阵，即当 `x` 是一维或二维数组时，返回一个相同大小和形状的数组。

In [3]:
import numpy as np
np.set_printoptions(linewidth=100) 

def sigmoid(x):

    # Implementation here
    return (np.where(x>0, 1, np.exp(x)))/(1 + np.exp(-np.abs(x)))

def softplus(x):

    # Implementation here
    return np.maximum(0, x) + np.log(1 + np.exp(-np.abs(x)))

np.random.seed(123)
vec = np.random.normal(size=6)
mat = np.random.normal(size=(5, 3))
print("Sigmoid(v) =\n", sigmoid(vec))
print("Sigmoid(m) =\n", sigmoid(mat))
print("Softplus(v) =\n", softplus(vec))
print("Softplus(m) =\n", softplus(mat))

Sigmoid(v) =
 [0.25244196 0.73053634 0.57027629 0.18148857 0.35925474 0.83908511]
Sigmoid(m) =
 [[0.08116076 0.39438602 0.78004631]
 [0.29593301 0.33650995 0.47634044]
 [0.81628676 0.34549479 0.39079256]
 [0.39308777 0.90078077 0.89905661]
 [0.73185488 0.59536432 0.67642017]]
Softplus(v) =
 [0.29094333 1.31132175 0.84461281 0.20026791 0.44512331 1.82687967]
Softplus(m) =
 [[0.08464411 0.50151249 1.51433825]
 [0.35088177 0.41024142 0.6469135 ]
 [1.69437919 0.42387573 0.49559644]
 [0.49937109 2.31042345 2.29319537]
 [1.31622694 0.90476816 1.12830942]]


(b) 推导 Sigmoid 和 Softplus 函数的导数，编写**数值稳定**的函数 `d_sigmoid(x)` 和 `d_softplus(x)` 计算对应的导数，同样要求适用于向量和矩阵。

$\sigma(x)=1/(1+\exp(-x)),\ \sigma'(x)=...$

$\mathrm{softplus}(x)=\log(1+\exp(x)),\ \mathrm{softplus}'(x)=...$

注意到 Sigmoid 和 Softplus 之间的联系了吗？

In [4]:
def d_sigmoid(x):

    return sigmoid(x)*(1-sigmoid(x))

def d_softplus(x):

    return sigmoid(x)

print("Sigmoid'(v) =\n", d_sigmoid(vec))
print("Sigmoid'(m) =\n", d_sigmoid(mat))
print("Softplus'(v) =\n", d_softplus(vec))
print("Softplus'(m) =\n", d_softplus(mat))

Sigmoid'(v) =
 [0.18871502 0.196853   0.24506124 0.14855047 0.23019077 0.13502129]
Sigmoid'(m) =
 [[0.07457369 0.23884569 0.17157406]
 [0.20835666 0.223271   0.24944023]
 [0.14996269 0.22612814 0.23807373]
 [0.23856977 0.08937477 0.09075383]
 [0.19624332 0.24090565 0.21887592]]
Softplus'(v) =
 [0.25244196 0.73053634 0.57027629 0.18148857 0.35925474 0.83908511]
Softplus'(m) =
 [[0.08116076 0.39438602 0.78004631]
 [0.29593301 0.33650995 0.47634044]
 [0.81628676 0.34549479 0.39079256]
 [0.39308777 0.90078077 0.89905661]
 [0.73185488 0.59536432 0.67642017]]


(c) 编写函数 `relu(x)` 和 `d_relu(x)` 来实现 ReLU 函数及其导数，$\mathrm{ReLU}(x)=\max(x,0)$，要求适用于向量和矩阵。对于不可导的点，可以将导数取为左导数或右导数。

In [6]:
def relu(x):
    return np.maximum(0, x)

def d_relu(x):
    return np.where(x>0, 1, 0)

print("ReLU(v) =\n", relu(vec))
print("ReLU(m) =\n", relu(mat))
print("ReLU'(v) =\n", d_relu(vec))
print("ReLU'(m) =\n", d_relu(mat))

ReLU(v) =
 [0.         0.99734545 0.2829785  0.         0.         1.65143654]
ReLU(m) =
 [[0.         0.         1.26593626]
 [0.         0.         0.        ]
 [1.49138963 0.         0.        ]
 [0.         2.20593008 2.18678609]
 [1.0040539  0.3861864  0.73736858]]
ReLU'(v) =
 [0 1 1 0 0 1]
ReLU'(m) =
 [[0 0 1]
 [0 0 0]
 [1 0 0]
 [0 1 1]
 [1 1 1]]


### 第3题

练习标量的反向传播算法。考虑一个两层的前馈神经网络（见第5周课件107页），其中数据和权重都是标量：

![](img/model1.png)

如下为正向的计算过程：

In [7]:
x = 1.2345
w1 = 0.111
b1 = 0.222
w2 = 0.333
b2 = -0.444

a0 = x
z1 = w1 * a0 + b1
a1 = sigmoid(z1)
z2 = w2 * a1 + b2
a2 = z2

yhat = a2
y = 5.4321

令损失函数为 $l=(y-\hat{y})^2$，则可以计算出 $l$ 对 $a_2=\hat{y}$ 的导数为 $\mathrm{d}l/\mathrm{d}a_2=2(a_2-y)$：

In [8]:
d_l_a2 = 2.0 * (a2 - y) # This is the "upstream derivative" associated with a2

现在将 $a_2$ 的导数反向传播给 $z_2$。首先计算 $a_2$ 对 $z_2$ 的“局部导数”：因为 $a_2=z_2$，所以局部导数为1。然后将“上游导数”乘以“局部导数”，即得到“下游导数”。

In [9]:
d_a2_z2 = 1.0 # The "local derivative" of a2 with respect to z2
d_l_z2 = d_l_a2 * d_a2_z2 # The "downstream derivative" of l with respect to z2

print(d_l_z2)

-11.360055548261299


接下来将 $z_2$ 的导数继续向下游传播。在上一层的计算中得到的“下游导数”现在变成了“上游导数”，进而向 $a_1$、$w_2$ 和 $b_2$ 传播。依然进行局部导数的计算，可以得到 $\mathrm{d}z_2/\mathrm{d}a_1=w_2$, $\mathrm{d}z_2/\mathrm{d}w_2=a_1$, $\mathrm{d}z_2/\mathrm{d}b_2=1$。

In [10]:
d_z2_a1 = w2
d_z2_w2 = a1
d_z2_b2 = 1.0

于是通过链式法则，将“上游导数”乘以“局部导数”得到“下游导数”。

In [11]:
d_l_a1 = d_l_z2 * d_z2_a1
d_l_w2 = d_l_z2 * d_z2_w2
d_l_b2 = d_l_z2 * d_z2_b2

print(d_l_a1)
print(d_l_w2)
print(d_l_b2)

-3.7828984975710127
-6.688862995036224
-11.360055548261299


请完成后续的过程，计算出 $\mathrm{d}l/\mathrm{d}w_1$ 和 $\mathrm{d}l/\mathrm{d}b_1$。

In [13]:
d_a1_z1 = d_sigmoid(z1)
d_l_z1 = d_l_a1 * d_a1_z1
print(d_a1_z1)

0.24211358617294854


In [14]:
d_z1_w1 = x
d_z1_b1 = 1.0

d_l_w1 = d_l_z1 * d_z1_w1
d_l_b1 = d_l_z1 * d_z1_b1
print(d_l_w1)
print(d_l_b1)

-1.1306675893376559
-0.9158911213751769


```py
d_l_w1 = ...
d_l_b1 = ...

print(d_l_w1)
print(d_l_b1)
```

### 第4题

现在考虑一个更实际的场景，首先，数据包含多个观测，每个观测占据一行：

In [37]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])

可以看出输入的维度为 $p=2$，输出的维度为 $d=1$，样本量为 $n=4$。我们将构建一个两层的前馈神经网络，其中隐藏层的维度为 $r=5$。计算流程如下：

![](img/model2.png)

$Z_1=XW_1+\mathbf{1}_nb_1^T,\quad A_1=\mathrm{softplus}(Z_1)$

$Z_2=A_1W_2+\mathbf{1}_nb_2^T,\quad A_2=\mathrm{sigmoid}(Z_2)$

其中 $\mathbf{1}_n$ 为元素全为1的 $n\times 1$ 向量，$W_1$ 为 $p\times r$ 矩阵，$b_1$ 为 $r\times 1$ 向量，$W_2$ 为 $r\times d$ 矩阵，$b_2$ 为 $d\times 1$ 向量。

In [17]:
p = 2
d = 1
n = 4
r = 5

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

a0 = x
ones = np.ones((n, 1))
z1 = a0.dot(w1) + ones.dot(b1.T)
a1 = softplus(z1)
z2 = a1.dot(w2) + ones.dot(b2.T)
a2 = sigmoid(z2)

phat = a2
print(phat)

[[0.99818247]
 [0.98868386]
 [0.99961553]
 [0.99139015]]


定义第 $i$ 个观测的损失函数为 $l(y_i,\hat{p}_i)=-y_i \cdot \log(\hat{p}_i)-(1-y_i) \cdot \log(1-\hat{p}_i)$，请推导出 $l$ 对 $\hat{p}_i$ 的导数。

$\mathrm{d}l/\mathrm{d}\hat{p}_i=...$

dl/dp = -y/p + (1-y)/(1-p)

定义整体的损失函数为 $L(y,\hat{p})=n^{-1}\sum_{i=1}^n l(y_i,p_i)$，请给出 $L$ 对 $\hat{p}_i$ 的导数。

$\mathrm{d}L/\mathrm{d}\hat{p}_i=...$

dL/dp = （1/n）* sigma(dl/dp) = （1/n）* sigma(-y/p + (1-y)/(1-p))

```py
d_l_a2 = ...
print(d_l_a2)

if d_l_a2.shape != a2.shape:
    print("Shapes do not match! Please redo the calculation.")
```

In [29]:
d_l_a2 = -y/a2+(1-y)/(1-a2)
print(d_l_a2)

if d_l_a2.shape != a2.shape:
    print("Shapes do not match! Please redo the calculation.")

[[550.1969833 ]
 [ -1.01144566]
 [ -1.00038462]
 [116.14603531]]


`d_l_a2` 是损失函数对 $A_2$ 的“上游导数”，我们需要将其传播给下游 $Z_2$。由于 $A_2=\mathrm{sigmoid}(Z_2)$，根据课件中反向传播的规则1，可以得到下游导数为

$\mathrm{d}L/\mathrm{d}Z_2=\mathrm{d}L/\mathrm{d}A_2\circ \mathrm{sigmoid}'(Z_2)$，

其中 $\mathrm{sigmoid}'$ 是 Sigmoid 的导数，$\circ$ 是向量或矩阵的逐元素相乘。

In [32]:
d_l_z2 = d_l_a2 * d_sigmoid(z2)
print(d_l_z2)

if d_l_z2.shape != z2.shape:
    print("Shapes do not match! Please redo the calculation.")

[[ 9.98182469e-01]
 [-1.13161398e-02]
 [-3.84471490e-04]
 [ 9.91390150e-01]]


接下来，再将 $Z_2$ 的“上游导数”传给 $A_1$、$W_2$ 和 $b_2$。根据规则2，

$\mathrm{d}L/\mathrm{d}A_1=(\mathrm{d}L/\mathrm{d}Z_2)W_2^T$，

$\mathrm{d}L/\mathrm{d}W_2=A_1^T(\mathrm{d}L/\mathrm{d}Z_2)$，

$\mathrm{d}L/\mathrm{d}b_2=(\mathrm{d}L/\mathrm{d}Z_2)^T\mathbf{1}_n$。

请根据如上公式计算对应的导数，并赋值给相应的变量。

In [34]:
d_l_a1 = np.dot(d_l_z2, w2.T)
d_l_w2 = np.dot(a1.T, d_l_z2)
d_l_b2 = np.dot(d_l_z2.T, ones)

print("d_A1:\n", d_l_a1)
print("d_W2:\n", d_l_w2)
print("d_b2:\n", d_l_b2)
if (d_l_a1.shape != a1.shape) or (d_l_w2.shape != w2.shape) or (d_l_b2.shape != b2.shape):
    print("Shapes do not match! Please redo the calculation.")

d_A1:
 [[-4.33561829e-01  2.20192074e+00  2.18281154e+00  1.00222900e+00  3.85484493e-01]
 [ 4.91517977e-03 -2.49626133e-02 -2.47459771e-02 -1.13620143e-02 -4.37013929e-03]
 [ 1.66995682e-04 -8.48117225e-04 -8.40756905e-04 -3.86030098e-04 -1.48477660e-04]
 [-4.30611576e-01  2.18693735e+00  2.16795819e+00  9.95409144e-01  3.82861392e-01]]
d_W2:
 [[1.02750997]
 [0.83975867]
 [3.23849943]
 [0.75532764]
 [0.63144648]]
d_b2:
 [[1.97787201]]


```py
d_l_a1 = ...
print("d_A1:\n", d_l_a1)

d_l_w2 = ...
print("d_W2:\n", d_l_w2)

d_l_b2 = ...
print("d_b2:\n", d_l_b2)

if (d_l_a1.shape != a1.shape) or (d_l_w2.shape != w2.shape) or (d_l_b2.shape != b2.shape):
    print("Shapes do not match! Please redo the calculation.")
```

请完成后续的过程，计算出 $\mathrm{d}L/\mathrm{d}W_1$ 和 $\mathrm{d}L/\mathrm{d}b_1$。

```py
d_l_w1 = ...
print("d_W1:\n", d_l_w1)

d_l_b1 = ...
print("d_b1:\n", d_l_b1)

if (d_l_w1.shape != w1.shape) or (d_l_b1.shape != b1.shape):
    print("Shapes do not match! Please redo the calculation.")
```

In [39]:
d_l_z1 = d_l_a1* d_softplus(z1)


d_l_w1 = np.dot(x.T, d_l_z1)
print("d_W1:\n", d_l_w1)

d_l_b1 = np.dot(d_l_z1.T, ones)
print("d_b1:\n", d_l_b1)

if (d_l_w1.shape != w1.shape) or (d_l_b1.shape != b1.shape):
    print("Shapes do not match! Please redo the calculation.")

d_W1:
 [[-0.20312091  0.39056744  1.7193081   0.29194397  0.05023874]
 [-0.19957874  0.38931434  1.70163664  0.28457846  0.04934995]]
d_b1:
 [[-0.34545219]
 [ 1.4375748 ]
 [ 3.48271794]
 [ 0.63080291]
 [ 0.19995514]]


### 第5题

将第4题中的步骤封装成三个函数：`forward()` 计算正向传播结果，得到预测值向量 `phat`，`loss()` 计算整体损失函数值，`backward()` 计算反向传播后各参数的导数。

In [42]:
def forward(x, w1, b1, w2, b2):

    a0 = x
    n = len(x)
    ones = np.ones((n, 1))
    z1 = a0.dot(w1) + ones.dot(b1.T)
    a1 = softplus(z1)
    z2 = a1.dot(w2) + ones.dot(b2.T)
    a2 = sigmoid(z2)
    # Implementation here
    return z1, a1, z2, a2

def loss_function(y, phat):
    loss = np.sum(-y * np.log(phat) - (1-y) * np.log(1 - phat))/len(y)
    # Implementation here
    return loss

def backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y):
    d_l_a2 = -y/a2+(1-y)/(1-a2)
    d_l_z2 = d_l_a2 * d_sigmoid(z2)
    d_l_a1 = np.dot(d_l_z2, w2.T)
    d_l_w2 = np.dot(a1.T, d_l_z2)
    d_l_b2 = np.dot(d_l_z2.T, ones)
    
    d_l_z1 = d_l_a1* d_softplus(z1)
    d_l_w1 = np.dot(x.T, d_l_z1)
    d_l_b1 = np.dot(d_l_z1.T, ones)

    # Implementation here
    return d_l_w1, d_l_b1, d_l_w2, d_l_b2

与之前的结果互相印证：

In [43]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])
p = 2
d = 1
n = 4
r = 5

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

z1, a1, z2, a2 = forward(x, w1, b1, w2, b2)
phat = a2
loss = loss_function(y, phat)
grads = backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y)

print("phat =\n", phat)
print("loss =", loss)
print("(dw1, db1, dw2, db2) =\n", grads)

phat =
 [[0.99818247]
 [0.98868386]
 [0.99961553]
 [0.99139015]]
loss = 2.7692224724634995
(dw1, db1, dw2, db2) =
 (array([[-0.20312091,  0.39056744,  1.7193081 ,  0.29194397,  0.05023874],
       [-0.19957874,  0.38931434,  1.70163664,  0.28457846,  0.04934995]]), array([[-0.34545219],
       [ 1.4375748 ],
       [ 3.48271794],
       [ 0.63080291],
       [ 0.19995514]]), array([[1.02750997],
       [0.83975867],
       [3.23849943],
       [0.75532764],
       [0.63144648]]), array([[1.97787201]]))


最后将这三步放在循环中，并利用梯度下降法拟合出 $x$ 和 $y$ 之间的函数关系。下面是一个完整的神经网络模型，我们可以修改隐藏层的维度。

In [44]:
x = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
y = np.array([[0.0],
              [1.0],
              [1.0],
              [0.0]])

n = x.shape[0]
p = x.shape[1]
d = y.shape[1]
r = 10

np.random.seed(123)
w1 = np.random.normal(size=(p, r))
b1 = np.random.normal(size=(r, 1))
w2 = np.random.normal(size=(r, d))
b2 = np.random.normal(size=(d, 1))

nepoch = 1000
learning_rate = 0.1

for i in range(nepoch):
    z1, a1, z2, a2 = forward(x, w1, b1, w2, b2)
    phat = a2
    loss = loss_function(y, phat)
    dw1, db1, dw2, db2 = backward(x, w1, b1, w2, b2, z1, a1, z2, a2, y)
    
    if i % 50 == 0:
        print(f"iteration {i}, loss = {loss}, prediction = {phat.squeeze()}")
        
    w1 = w1 - learning_rate * dw1
    b1 = b1 - learning_rate * db1
    w2 = w2 - learning_rate * dw2
    b2 = b2 - learning_rate * db2

iteration 0, loss = 4.616747553776374, prediction = [5.14780976e-04 3.24250638e-04 2.94601507e-05 9.50104717e-06]
iteration 50, loss = 0.2669069138966255, prediction = [0.2728565  0.80454453 0.74301711 0.20901878]
iteration 100, loss = 0.0807818316020853, prediction = [0.09480138 0.93413655 0.91974612 0.06922359]
iteration 150, loss = 0.03643732549182101, prediction = [0.04406834 0.96962758 0.96372589 0.0323539 ]
iteration 200, loss = 0.021446794150200302, prediction = [0.02621544 0.98200007 0.97872241 0.01936098]
iteration 250, loss = 0.014572899171769703, prediction = [0.01790405 0.9877339  0.98559616 0.01328575]
iteration 300, loss = 0.010786440812915396, prediction = [0.01329063 0.99090781 0.98937418 0.00990024]
iteration 350, loss = 0.008442033314506936, prediction = [0.01042122 0.99287819 0.99170758 0.00778747]
iteration 400, loss = 0.006869707110741481, prediction = [0.00849105 0.9942018  0.99326881 0.00636217]
iteration 450, loss = 0.005752508205655098, prediction = [0.00711671